trigger: none

resources:
  pipelines:
  - pipeline: ToDosDemoServices
    source: Kros.AspNetCore.BestPractices - CI
    # trigger: true
  - pipeline: ToDosDemoClient
    source: Kros.Angular.BestPractices - CI
    # trigger: true

variables:
  azureSubscriptionName: 'KROS DEVEL SUBSCRIPTION'
  Stage: empty

stages:
- stage: Development
  displayName: 'Deploy to development'
  jobs:
  - deployment: Services
    pool: Default
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ToDosDemoServices
            artifact: drop
            displayName: 'Download services artifacts'

          - task: AzureCLI@2
            displayName: Deploy microservices
            inputs:
              azureSubscription: $(azureSubscriptionName)
              scriptType: ps
              scriptLocation: '$(Pipeline.Workspace)/ToDosDemoServices/drop/pipelines/Deploy-Async.ps1'
              arguments: -microservices 'ToDos', 'Authorization', 'Organizations', 'ApiGateway'

          - template: postman-tests.yml

  - deployment: Client
    pool: Default
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-client.yml
            parameters:
              storageAccount: 'krosdemostorage'