trigger: none

resources:
  pipelines:
  - pipeline: ToDosDemoServices
    source: Kros.AspNetCore.BestPractices - CI
    # trigger: true
  - pipeline: ToDosDemoClient
    source: Kros.Angular.BestPractices - CI
    # trigger: true

variables:
  azureSubscriptionName: 'KROS DEVEL SUBSCRIPTION'
  ConnectionStrings.DefaultConnection: ''
  Stage: empty

stages:
- stage: Development
  displayName: 'Deploy to development'
  variables:
    - template: variables-development.yml
  jobs:
  - deployment: Services
    pool: Default
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ToDosDemoServices
            artifact: drop
            displayName: 'Download services artifacts'

          # - template: deploy-services.yml

          - template: postman-tests.yml

  # - deployment: Client
  #   pool: Default
  #   environment: development
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - template: deploy-client.yml
  #           parameters:
  #             storageAccount: 'krosdemostorage'