trigger: none

resources:
  pipelines:
  - pipeline: ToDosDemoServices
    source: Kros.AspNetCore.BestPractices - CI
    #trigger: false
  - pipeline: ToDosDemoClient
    source: Kros.Angular.BestPractices - CI
    #trigger: false

variables:
  azureSubscriptionName: 'KROS DEVEL SUBSCRIPTION'
  Stage: empty

stages:
- stage: Development
  displayName: 'Deploy to development'
  jobs:
  - deployment: Services
    pool:
      name: Default
      demands: Agent.ComputerName -equals build1
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ToDosDemoServices
            artifact: drop
            displayName: 'Download services artifacts'

          - task: AzureCLI@2
            displayName: Deploy microservices
            inputs:
              azureSubscription: $(azureSubscriptionName)
              scriptType: ps
              scriptLocation: scriptPath
              scriptPath: '$(Pipeline.Workspace)\ToDosDemoServices\drop\pipelines\Deploy-Async.ps1'
              arguments: -microservices 'ToDos', 'Authorization', 'Organizations', 'ApiGateway' -artifactPath '$(Pipeline.Workspace)\ToDosDemoServices\drop\'

          - template: postman-tests.yml

  - deployment: Client
    pool:
      name: Default
      demands: Agent.ComputerName -equals build1
    workspace:
      clean: all
    environment: development
    dependsOn: Services
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-client.yml
            parameters:
              storageAccount: 'krosdemostorage'

          - template: cypress-tests.yml

